-- RAG TRAINING DATABASE SCHEMA
-- Generated by Enhanced Rural Network Simulation

CREATE TABLE Nodes (
    node_id VARCHAR(50) PRIMARY KEY,
    node_name VARCHAR(100) NOT NULL,
    layer_id INT NOT NULL,
    node_type_id INT NOT NULL,
    ip_address VARCHAR(50),
    location VARCHAR(200),
    status VARCHAR(20),
    last_heartbeat TIMESTAMP,
    current_cpu_load_percent DECIMAL(5,2),
    current_memory_load_percent DECIMAL(5,2),
    current_bandwidth_util_percent DECIMAL(5,2),
    max_capacity_units DECIMAL(10,2),
    operational_state VARCHAR(20),
    firmware_version VARCHAR(50),
    last_config_change TIMESTAMP
);

CREATE TABLE Links (
    link_id VARCHAR(100) PRIMARY KEY,
    source_node_id VARCHAR(50) NOT NULL,
    destination_node_id VARCHAR(50) NOT NULL,
    link_type VARCHAR(50),
    total_bandwidth_mbps DECIMAL(10,2),
    current_bandwidth_util_percent DECIMAL(5,2),
    latency_ms DECIMAL(8,3),
    packet_loss_rate DECIMAL(8,6),
    status VARCHAR(20),
    is_redundant BOOLEAN,
    timestamp TIMESTAMP
);

CREATE TABLE Anomalies (
    anomaly_id VARCHAR(100) PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    node_id VARCHAR(50) NOT NULL,
    severity_classification VARCHAR(20),
    anomaly_description TEXT,
    root_cause_indicators TEXT,
    affected_components TEXT,
    time_to_failure VARCHAR(50),
    status VARCHAR(20),
    healing_recommendation_id INT,
    anomaly_type_id INT
);

CREATE TABLE RecoveryTactics (
    tactic_id INT PRIMARY KEY,
    tactic_name VARCHAR(100) NOT NULL,
    description TEXT,
    estimated_downtime_seconds INT,
    risk_level VARCHAR(20),
    is_automated_capable BOOLEAN,
    policy_id INT
);

CREATE TABLE Policies (
    policy_id INT PRIMARY KEY,
    policy_name VARCHAR(200) NOT NULL,
    policy_category VARCHAR(50),
    description TEXT,
    full_text_reference TEXT,
    impact_on_recovery TEXT,
    impact_on_load_distribution TEXT,
    last_updated DATE
);

CREATE TABLE TrafficFlows (
    flow_id VARCHAR(100) PRIMARY KEY,
    source_node_id VARCHAR(50) NOT NULL,
    destination_node_id VARCHAR(50) NOT NULL,
    traffic_volume_mbps DECIMAL(10,2),
    traffic_type VARCHAR(50),
    priority VARCHAR(20),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    timestamp TIMESTAMP
);

CREATE TABLE NetworkLayers (
    layer_id INT PRIMARY KEY,
    layer_name VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE NodeTypes (
    node_type_id INT PRIMARY KEY,
    type_name VARCHAR(50) NOT NULL,
    description TEXT,
    typical_role TEXT
);


-- REFERENCE DATA
INSERT INTO NetworkLayers VALUES
(1, 'Core', 'High-capacity backbone routing and switching'),
(2, 'Distribution', 'Regional traffic aggregation and distribution'),
(3, 'Access', 'End-user connection points and edge access');

INSERT INTO NodeTypes VALUES
(1, 'Core_Router', 'High-performance core network router', 'Inter-region routing and traffic management'),
(2, 'Distribution_Switch', 'Regional distribution switch', 'Traffic aggregation and VLAN management'),
(3, 'Access_Point', 'End-user access point', 'Direct user connectivity and edge services');

